### ISSUE TITLE
Transition to new workflow

### ISSUE THREAD

**Issue by aaronjridley** [GITMCode/GITM#10]
Old workflow has been very ad hoc.  We will formalize the new workflow:

- Develop a contributing.md writeup that describes the new workflow
- Create a develop branch
- Write an e-mail to the user group describing this process

**Comment by abukowski21** [comment]
First two steps are done. Workflow is implemented & tested. Works as expected.

Still need to make a users/maintainers/*something* group email list.

**Comment by abukowski21** [comment]
Email list created.
