### ISSUE TITLE
Make a repository of input files and model results

### ISSUE THREAD

**Issue by aaronjridley** [GITMCode/GITM#13]
There should be some examples of functionality tests in the GITM repo, but there should be longer, science-grade simulation input files and at least log files in the new repository.

Dan's current repository is located here: https://github.com/spacecataz/swmf_runfiles

This is a good starting space, but should be a bit cleaner in the organizational structure.

**Comment by abukowski21** [comment]
Located here, in case anyone finds this old thread:

https://github.com/GITMCode/GITM_Input_Files/tree/main
